# Generated by Django 4.1.7 on 2023-03-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vehicle_processed', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=30)),
                ('vehicle_processed', models.CharField(max_length=30)),
                ('org_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veh_api.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrganisationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=30)),
                ('vehicle_processed', models.CharField(max_length=30)),
                ('sub_org_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veh_api.suborganisation')),
            ],
        ),
    ]
