# Generated by Django 4.1.7 on 2023-04-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veh_api', '0004_alter_suborganisation_percentage_operations_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborganisationdata',
            name='percentage_operations_processed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suborganisationdata',
            name='percentage_ticketed_matches',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suborganisationdata',
            name='ticketed_matches_identified',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suborganisationdata',
            name='vehicle_processed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suborganisationdata',
            name='wanted_matches_identified',
            field=models.IntegerField(null=True),
        ),
    ]
